---
application:
  name: "irregular-verb-site"
  project: "irregular-verbs"
  organization: "QoveryCommunity"
routers:
- name: "main-irregular-verb-site"
  routes:
  - application_name: "irregular-verb-site"
    paths:
    - "/*"
databases:
- type: postgresql # database type
  version: "11.5" # database version
  name: verbs # database name (must be unique)
